<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */

    'namespace' => null,

    'scan' => [

        'enabled' => true,

        'paths' => [
            // It's important to enable scan and search for a lowercase
            // modules directory, otherwise it searches in Modules/ which
            // will return nothing on case-sensitive systems.
            base_path('modules/*'),
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Module Stubs
    |--------------------------------------------------------------------------
    |
    | Default module stubs.
    |
    */

    'stubs' => [

        'enabled' => true,

        'path' => resource_path('modules/stubs'),

        'files' => [
            'config' => 'config/config.php',
            'views/master' => 'resources/views/layouts/master.blade.php',
            'views/index' => 'resources/views/pages/index.blade.php',
        ],

        'replacements' => [
            'json' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'scaffold/config' => ['STUDLY_NAME'],
            'views/index' => ['LOWER_NAME'],
            'views/master' => ['STUDLY_NAME'],
        ],

        'resources' => [
            'provider' => 'src/Providers',
        ],

    ],

    'paths' => [

        /*
        |--------------------------------------------------------------------------
        | Modules path
        |--------------------------------------------------------------------------
        |
        | This path used for save the generated module. This path also will be added
        | automatically to list of scanned folders.
        |
        */

        'modules' => base_path('modules'),

        /*
        |--------------------------------------------------------------------------
        | Generator path
        |--------------------------------------------------------------------------
        |
        | Here you may update the modules generator path.
        |
        */

        'generator' => [
            'styles' => 'resources/assets/styles',
            'scripts' => 'resources/assets/scripts',
            'lang' => 'resources/translations',
            'test/feature' => 'tests/Feature',
            'test/unit' => 'tests/Unit',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    |
    */

    'composer' => [
        'vendor' => 'sebastiaanluca',
        'author' => [
            'name' => 'Sebastiaan Luca',
            'email' => 'hello@sebastiaanluca.com',
        ],
    ],

];
